language: python
env:
  - TASK_VERSION=v2.4.4
python:
  - "3.4"
install:
  - pip install coveralls
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential cmake uuid-dev g++-4.8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
  - git clone https://git.tasktools.org/scm/tm/task.git
  - cd task
  - git checkout $TASK_VERSION
  - git clean -dfx
  - cmake .
  - make
  - sudo make install
  - task --version
before_script:
  - cd $TRAVIS_BUILD_DIR
script:
  coverage run --source=tarenalib setup.py test
after_success:
  coveralls
